apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectapp
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projectapp
  template:
    metadata:
      labels:
        app: projectapp
    spec:
      containers:
        - name: myapp
          image: michaelfawzy/myapp:5
          ports:
            - containerPort: 8080
