---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectapp
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: projectapp
  namespace: demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: projectapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: projectapp
subjects:
- kind: ServiceAccount
  name: projectapp
  namespace: demo