apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projectapp
spec:
  project: default
  source:
    repoURL: https://github.com/Ahetoo7/eyouth-argocd
    targetRevision: HEAD
    path: apps/nginx3
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
